name: Tauri builder
on:
  push

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install Tauri
        run: npm install tauri
      - name: Install other dependencies
        run: npm install
      - name: Bump package version
        id: bumping-version
        uses: jpb06/bump-package@latest
        with:
          should-default-to-patch: true
      - name: Tag things :3
        uses: Klemensas/action-autotag@stable
        id: tagger
        with:
          GITHUB_TOKEN: ${{ secrets.TOKEN}}
      - name: Build
        run: npm run tauri build
      - name: Release
        uses: svenstaro/upload-release-action@2.9.0
        with:
          file: /src-tauri/target/release/bundle/msi/*
          release_name: Nightly Build (v.${{ steps.tagger.outputs.version }})
          prerelease: true
          make_latest: false
